//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Kitaplar()
        {
            this.Tbl_Hareket = new HashSet<Tbl_Hareket>();
        }
    
        public int ID { get; set; }
        public string Ad { get; set; }
        public Nullable<byte> Kategori { get; set; }
        public Nullable<int> Yazar { get; set; }
        public string BasımYıl { get; set; }
        public string Yayınevi { get; set; }
        public string Sayfa { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string KitapResim { get; set; }
        public string Detay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Hareket> Tbl_Hareket { get; set; }
        public virtual Tbl_Kategoriler Tbl_Kategoriler { get; set; }
        public virtual Tbl_Yazarlar Tbl_Yazarlar { get; set; }
    }
}
